import Head from 'next/head'
import Image from 'next/image'
import Comments from '../components/Comments'
import styles from '../styles/Home.module.css'
import { connect } from '@planetscale/database'
import { useEffect } from 'react'
import { Box, Drawer, Flex, Spacer, Text } from '@chakra-ui/react'
import DrawerExample from '../components/DrawerComp'
import ColorToggle from '../components/ColorToggle'
import useAuthStore from '../store/authStore'
import UserDrawer from '../components/UserDrawer'

const config = {
  host: process.env.NEXT_PUBLIC_DATABASE_HOST,
  username: process.env.NEXT_PUBLIC_DATABASE_USERNAME,
  password: process.env.NEXT_PUBLIC_DATABASE_PASSWORD
}




export default function Home() {


  const { userProfile } = useAuthStore();



  useEffect(() => {
    //getData()

  }, [])


  /*   async function getData() {
      const conn = connect(config)
      const results = await conn.execute('')
      return results
  
    } */

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex p={6} alignItems="center" justifyContent="center">
        <DrawerExample />

        <Spacer />

        <UserDrawer />



      </Flex>











    </div>
  )
}


