import Head from 'next/head'
import Image from 'next/image'
import Comments from '../components/Comments'
import styles from '../styles/Home.module.css'
import { connect } from '@planetscale/database'
import { useEffect, useState } from 'react'
import { Box, Container, Drawer, Flex, SimpleGrid, Spacer, Text, useColorModeValue, VStack } from '@chakra-ui/react'
import DrawerExample from '../components/DrawerComp'
import ColorToggle from '../components/ColorToggle'
import useAuthStore from '../store/authStore'
import UserDrawer from '../components/UserDrawer'
import GuestComp from '../components/GuestComp'
import TabsComp from '../components/TabsComp'

const config = {
  host: process.env.NEXT_PUBLIC_DATABASE_HOST,
  username: process.env.NEXT_PUBLIC_DATABASE_USERNAME,
  password: process.env.NEXT_PUBLIC_DATABASE_PASSWORD
}




export default function Home() {


  const [auth, setAuth] = useState()
  const { userProfile } = useAuthStore();
  const bgcolor = useColorModeValue('gray.200', 'gray.600')
  const seccolor = useColorModeValue('gray.400', 'gray.600')



  useEffect(() => {
    if (userProfile) {
      setAuth(true)
      console.log('user exists')
    }

    if (!userProfile) {
      setAuth(false)
    }



  }, [userProfile])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex gap={0} direction='column' mt={5} bg={bgcolor} justifyContent='center' borderTopLeftRadius={10} borderTopRightRadius={10}>
        {auth ? <DrawerExample /> : <GuestComp auth={auth} setAuth={setAuth} />}


        {auth ? (<Flex bg={seccolor} w='full' direction='column'>
          <TabsComp />


        </Flex>
        ) : null}



      </Flex>











    </div>
  )
}


