import Head from 'next/head'
import Image from 'next/image'
import Comments from '../components/Comments'
import styles from '../styles/Home.module.css'
import { connect } from '@planetscale/database'
import { useEffect, useState } from 'react'
import { Box, Container, Drawer, Flex, SimpleGrid, Spacer, Text, VStack } from '@chakra-ui/react'
import DrawerExample from '../components/DrawerComp'
import ColorToggle from '../components/ColorToggle'
import useAuthStore from '../store/authStore'
import UserDrawer from '../components/UserDrawer'
import GuestComp from '../components/GuestComp'

const config = {
  host: process.env.NEXT_PUBLIC_DATABASE_HOST,
  username: process.env.NEXT_PUBLIC_DATABASE_USERNAME,
  password: process.env.NEXT_PUBLIC_DATABASE_PASSWORD
}




export default function Home() {


  const [auth, setAuth] = useState()
  const { userProfile } = useAuthStore();



  useEffect(() => {
    if (userProfile) {
      setAuth(true)
      console.log('user exists')
    }

    if (!userProfile) {
      setAuth(false)
    }



  }, [userProfile])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex gap={4} direction='column' mt={10}>
        {auth ? <DrawerExample /> : <GuestComp auth={auth} setAuth={setAuth} />}


        <Spacer />

        <Box bg='gray.400' w='full' h={100}>

        </Box>



      </Flex>











    </div>
  )
}


